import {StyleSheet} from 'react-native';
import {theme} from '../../../constants/colors';
import {getSize} from '../../../constants/constant';

const styles = StyleSheet.create({
  safearea: {backgroundColor: theme.colors.background},
  container: {
    backgroundColor: theme.colors.primary,
    // backgroundColor: 'red',
    // padding: 15,
    // justifyContent: 'center',
    height: '100%',
  },
  headerContainer: {
    height: '40%',
    backgroundColor: theme.colors.background,
    justifyContent: 'flex-end',
    // alignItems: 'center',
    borderBottomEndRadius: 40,
    borderBottomLeftRadius: 40,
    padding: 30,
  },
  childContainer: {
    // shadowColor: theme.colors.darkShalow,
    // shadowOffset: {width: 0, height: 0},
    // shadowOpacity: 0.3,
    // borderColor: 'lightgray',
    // borderWidth: 0.2,
    paddingVertical: 15,
    // paddingHorizontal: 5,
    margin: 20,
  },
  title: {
    color: theme.colors.textGray,
    fontWeight: '400',
    paddingHorizontal: 10,
    fontSize: getSize(16),
  },
  inputField: {
    borderColor: theme.colors.blue,
    borderWidth: 0.2,
    borderRadius: 8,
    marginBottom: 20,
    paddingHorizontal: 15,
    marginHorizontal: 10,
    marginTop: 10,
    height: 40,
    fontSize: getSize(16),
  },
  loginButton: {
    backgroundColor: theme.colors.red,
    height: 40,
    width: 100,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    marginStart: 10,
  },
  buttonText: {color: theme.colors.white, fontSize: getSize(16)},
  buttonTextBold: {
    color: theme.colors.red,
    fontSize: getSize(16),
    fontWeight: 'bold',
    marginStart: 30,
  },
  headerTitle: {
    fontSize: 48,
    fontWeight: '600',
    marginBottom: 30,
    color: theme.colors.red,
  },
  socialContainer: {
    flexDirection: 'row',
    height: 50,
    alignItems: 'center',
  },
  socialTouchable: {
    borderRadius: 13,
    borderColor: theme.colors.white,
    borderWidth: 0.2,
    height: 30,
    width: 42,
    alignItems: 'center',
    justifyContent: 'center',
    // shadowColor: theme.colors.darkShalow,
    // shadowOffset: {width: 0, height: 0.8},
    // shadowOpacity: 0.4,
    marginEnd: 12,
  },
  socialIcons: {width: 22, height: 22, resizeMode: 'contain'},
  checkIcon: {
    width: 15,
    height: 15,
    marginEnd: 20,
  },
  privacyText: {
    color: theme.colors.textGray,
    fontSize: getSize(16),
  },
  privacyCheckContainer: {
    marginVertical: 30,
    alignItems: 'center',
    flexDirection: 'row',
    marginStart: 15,
  },
  orText: {color: theme.colors.gray},
  buttonContainer: {flexDirection: 'row', alignItems: 'center'},
});
export default styles;
